language: node_js

node_js:
  - node

notifications:
  email: true

deploy:
  before_install:
    - sudo apt-get update
    - sudo apt-get install -y hugo
  before_script:
    - yarn
    - hugo --minify
  script: echo test
  on:
    tags: true
